### ISSUE TITLE
Win the game

### ISSUE THREAD

**Issue by RafaelS95** [drdreo/risikonline#128]
make game winnable

- trigger events
- check in backend

**Comment by RafaelS95** [comment]
function gameOver will be triggered when one player occupies all countries. The check is in occupyCountry. 

TODOs:
define when a player has won ( eliminate all enemies, get all countries, etc)
display end screen with interesting statistics (most lucky player, most eliminations, etc)

**Comment by drdreo** [comment]
Win condition is not to occupy all countries, but to eliminate all other players!
