### ISSUE TITLE
Bot vs Bot mode

### ISSUE THREAD

**Issue by davidHolzmann** [drdreo/risikonline#160]
**Is your feature request related to a problem? Please describe.**
Bots need to be tested to figure out if their strategy is viable. To do so, letting bots play against each other without a human player should be a good and time-saving approach.

**Describe the solution you'd like**
There should be a route for creating a game where only bots can be added and no human player is required. This game mode should have adjusted configs to reduce the timeout a bot waits between moves.

**Comment by drdreo** [comment]
We could add a mode selctor at home page. Choose from normal - spectator - public private.
When chosen spectator, you are added to the game as Spectator and are redirected to the normal lobby where you can add bots. I suggest adding a spectator area in the UI where all current spectators are listed. Got enough room there. Above crown selector.

Need to clarify what a Spectator is. References #144
