### ISSUE TITLE
Bot can't attack from 2 countries in the same turn

### ISSUE THREAD

**Issue by davidHolzmann** [drdreo/risikonline#162]
**Describe the bug**
When a bot attacks a country of yours and wins, them goes on to attack another country of yours from a different country, the game breaks. No more actions are possible after that. Both of the attacks have to happen in the same turn.

**To Reproduce**
1. create a game with at least one bot
2. let the bot gather enough units so that it will attack you and then go on attacking after capturing your country (~10)
3. See error

**Expected behavior**
The bot should be able to attack from more than one country in it's Attack/Expand phase.

**Comment by drdreo** [comment]
@davidHolzmann is this done already?

**Comment by davidHolzmann** [comment]
> @davidHolzmann is this done already?

yes. this was fixed with the battle view remake afaik
