### ISSUE TITLE
Battle Modal

### ISSUE THREAD

**Issue by drdreo** [drdreo/risikonline#38]
Design of the modal.
Refactor of integration.

**Comment by drdreo** [comment]
https://www.w3schools.com/code/tryit.asp?filename=FXUVUXJX27QX


-webkit-clip-path: polygon(0 0, 100% 0, 85% 100%, 0% 100%);
    /* clip-path: polygon(0 0, 100% 0, 85% 100%, 0% 100%); */

**Comment by RafaelS95** [comment]
This was finished in the BattleTurn branch.
