### ISSUE TITLE
SVG Filters/Animations for selected and bordering countries

### ISSUE THREAD

**Issue by davidHolzmann** [drdreo/risikonline#76]
**Is your feature request related to a problem? Please describe.**
The users attention has to be brought to the part of the map that is changing, so animations or filters to visualize it would be nice.

**Describe the solution you'd like**
The selected country of the user should marked in a way so that he knows how he can interact with it. E. g. red for an enemy country, green for an ally, ...
Same for the bordering countries of the selected one.

**Describe alternatives you've considered**
Lifting the selected country up with a box-shadow, doesn't work in SVGs.

**Comment by drdreo** [comment]
Why ain't lifting an option? Shadow is not a must have imo. Moving the svg up and then copy the same path like the first solution we head in the beginning.

Additionally, we could create a highlight-helper layer where we copy the selected path to overlay countries, kind of a z-index replacement. So the shadow or highlights are always above all others. 
Right now they look kinda messy, being below other countries sometimes.
