### ISSUE TITLE
Animate from where to where units move

### ISSUE THREAD

**Issue by davidHolzmann** [drdreo/risikonline#90]
**Describe the solution you'd like**
When you move from one country to another with your units there should be a line displayed from where to where the units move. The line should also animate the direction of the movement.

**Comment by drdreo** [comment]
@davidHolzmann is this done?

**Comment by davidHolzmann** [comment]
> @davidHolzmann is this done?

nope, deswegen das wontfix label
Ich glaub da haben uns die Daten gefehlt von wo der player wo hin geht. Teilweise ist es aber ersichtlich an den Einheiten, die nach oben fahren und faden wenn welche dazu oder weg kommen.
