### ISSUE TITLE
Success Responses for Turn Events

### ISSUE THREAD

**Issue by drdreo** [drdreo/risikonline#92]
On joinWar i need to get imformed if it was successfull, to set the clientside turnPhase to waiting.

**Describe the solution you'd like**
Send Events after user did something good.

**Comment by RafaelS95** [comment]
What responses do you need? How they should be called? Or do you just need a success and it will be checked in the frontend what the user did?

**Comment by drdreo** [comment]
Currently, i only need a `Turn.End` event when the player has finished. Either after skipping all phases or finishing maneuvering or successfully joining war. The event is already subscribed on the client.

But then we can not react to specific cases like success messages for different things the player did that easily.
Having a request <-> response chain is straight forward but not needed, yet. We can skip this issue because sending the `Turn.End` event is sufficient.
