### ISSUE TITLE
Game state store eventname

### ISSUE THREAD

**Issue by drdreo** [drdreo/risikonline#96]
References #35 
**Is your feature request related to a problem? Please describe.**
Need to send the player his current turnPhase when he reconnects like   ```socket.emit(turnPhase);```
Where the turnPhase needs to be from enum Turn e.q.: Turn.JoinWar.

I cant access the turn phase in the game.service because it is not stored, but hardcoded in the Game

**Describe the solution you'd like**
I would like to store the phase inside the state to access it via `game.state.phase` or something like this.
Then i can easily send the player his turnphase if its his turn like
```socket.emit(currentGame.state.phase);```

**Additionally** 
This is called when changing the turn of the active player
  ```
  // START JOIN WAR
      this.addNewPlayerCommand(Turn.JoinWar, currentPlayer.id);
      this.state = this.joinWarState;
```
could be refactored to not hardcode the phase

  ```
  // START JOIN WAR
      this.state = this.joinWarState;
      this.addNewPlayerCommand( this.state.phase, currentPlayer.id);

```

**Comment by RafaelS95** [comment]
Better solution - make a reconnectToGame function for each state. Each state handles the reconnect on its own. No need for saving the phase in backend code

**Comment by drdreo** [comment]
Also possible. But the only difference is that the state calls the correct turn event via a command which also would be hardcoded. And every state does the same thing. Since the state is the actual turn phase and only can have a single turn event for the client it wouldn’t hurt to store that aswell if we need the phase somewhere else and not only when reconnecting

**Comment by RafaelS95** [comment]
Not every state does the same. Best example is the recruit state. Here the client needs not only the Turn phase but also data like how many units he can recruit. All other states are the same but this can also change in the future. Like disconnecting in the middle of a battle. There will also be required data.

**Comment by drdreo** [comment]
Dru. Makes sense to me. Let's do it this way.
